"""
sisepuede/calibration/crosswalk_to_latex.py

Render the IEA <-> SISEPUEDE energy crosswalk CSV as a LaTeX longtable
snippet for inclusion in the energy-calibration tech note.

The output file is *not* a standalone document; it is meant to be pulled
into the tech note via ``\\input{...}``. One LaTeX row is emitted per SSP
output variable, so a single (balance, product) pair that aggregates over N
SSP fields produces N rows.

Usage
-----
    python -m sisepuede.calibration.crosswalk_to_latex
    python -m sisepuede.calibration.crosswalk_to_latex \\
        --in  sisepuede/ref/data_crosswalks/sisepuede_iea_energy_crosswalk.csv \\
        --out docs/latex/iea_ssp_crosswalk_table.tex

Both arguments are optional; defaults assume the repo root layout.
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import List

import pandas as pd


# ── Defaults aligned with repo layout ────────────────────────────────────────
_REPO_ROOT = "/Users/dianamendez/feature-energy-calibration"

DEFAULT_IN  = os.path.join(
    _REPO_ROOT,
    "sisepuede", "ref", "data_crosswalks", "sisepuede_iea_energy_crosswalk.csv",
)
DEFAULT_OUT = os.path.join(
    "/Users/dianamendez/sisepuede-data/",
    "tables", "iea_ssp_crosswalk_table.tex",
)
DEFAULT_FUEL_MAP_OUT = os.path.join(
    "/Users/dianamendez/sisepuede-data/",
    "tables", "iea_fuel_map_table.tex",
)


# Separator between SSP field names inside one CSV cell (matches
# build_iea_energy_crosswalk._VAR_SEP).
_VAR_SEP = ":"


def _escape_latex(s: str) -> str:
    """Escape LaTeX special characters that occur in SSP field names."""
    if s is None:
        return ""
    return (
        str(s)
        .replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("{", r"\{")
        .replace("}", r"\}")
    )


def _split_ssp_vars(cell: str) -> List[str]:
    if cell is None or (isinstance(cell, float) and pd.isna(cell)):
        return []
    parts = [p.strip() for p in str(cell).split(_VAR_SEP)]
    return [p for p in parts if p and not p.startswith("--")]


def _render_longtable(df: pd.DataFrame) -> str:
    """Render the exploded crosswalk DataFrame as a LaTeX longtable.

    df is expected to have columns:
        iea_balance_code, iea_product_code, sisepuede_subsector,
        ssp_variable, aggregation, mapping_quality
    where ssp_variable is a single SSP field name (already exploded).

    Rows are visually grouped by (iea_balance_code, iea_product_code): the
    IEA cells are blanked on continuation rows so a multi-row block reads as
    a single mapping with several SSP fields.
    """

    head = r"""\begingroup
\footnotesize
\setlength{\tabcolsep}{4pt}
\renewcommand{\arraystretch}{1.05}
\begin{longtable}{@{}p{0.10\linewidth} p{0.12\linewidth} p{0.07\linewidth} p{0.38\linewidth} p{0.08\linewidth} p{0.12\linewidth}@{}}
\caption{IEA $\leftrightarrow$ SISEPUEDE crosswalk: one row per SSP output variable. Variables sharing an IEA (balance, product) cell are aggregated (\texttt{sum} or \texttt{direct}). \emph{Generated by} \texttt{crosswalk\_to\_latex.py}.}\label{tab:xw_full}\\
\toprule
IEA balance & IEA product & SSP subsector & SSP output variable & Agg. & Quality \\
\midrule
\endfirsthead
\multicolumn{6}{c}{\emph{Table~\ref{tab:xw_full} continued from previous page}}\\
\toprule
IEA balance & IEA product & SSP subsector & SSP output variable & Agg. & Quality \\
\midrule
\endhead
\midrule
\multicolumn{6}{r}{\emph{continued on next page}}\\
\endfoot
\bottomrule
\endlastfoot
"""

    body_lines = []
    prev_key = None
    for _, r in df.iterrows():
        key = (r["iea_balance_code"], r["iea_product_code"])
        if key == prev_key:
            bal_cell, prod_cell, sub_cell = "", "", ""
        else:
            bal_cell  = _escape_latex(r["iea_balance_code"])
            prod_cell = _escape_latex(r["iea_product_code"])
            sub_cell  = _escape_latex(r["sisepuede_subsector"])
            prev_key  = key

        body_lines.append(
            " & ".join([
                bal_cell,
                prod_cell,
                sub_cell,
                r"\texttt{" + _escape_latex(r["ssp_variable"]) + "}",
                _escape_latex(r["aggregation"]),
                _escape_latex(r["mapping_quality"]),
            ]) + r" \\"
        )
        # Add a thin separator after each (balance, product) block to make
        # the multi-row groups visually obvious.
        # (We only add it when the *next* row will change the key; we don't
        # know that yet, so we add it lazily on the row *after*.)

    tail = "\n\\end{longtable}\n\\endgroup\n"
    return head + "\n".join(body_lines) + tail


def build_table(path_in: str, path_out: str) -> str:
    """Read the crosswalk CSV at ``path_in`` and write a LaTeX longtable to
    ``path_out``. Returns ``path_out`` for convenience."""

    df_raw = pd.read_csv(path_in)

    # Drop comment / section-header rows: those have no SSP output variables.
    df_raw = df_raw.dropna(subset=["sisepuede_output_variables"]).copy()

    # Explode the colon-separated SSP variable list into one row per variable.
    rows = []
    for _, r in df_raw.iterrows():
        ssp_vars = _split_ssp_vars(r["sisepuede_output_variables"])
        if not ssp_vars:
            continue
        for v in ssp_vars:
            rows.append({
                "iea_balance_code":   r["iea_balance_code"],
                "iea_product_code":   r["iea_product_code"],
                "sisepuede_subsector": r["sisepuede_subsector"],
                "ssp_variable":       v,
                "aggregation":        r["aggregation"],
                "mapping_quality":    r["mapping_quality"],
            })
    df = pd.DataFrame(rows)

    # Sort for stable output: by IEA balance, then product, then SSP variable.
    df = df.sort_values(
        ["iea_balance_code", "iea_product_code", "ssp_variable"],
        kind="stable",
    ).reset_index(drop=True)

    tex = _render_longtable(df)

    os.makedirs(os.path.dirname(path_out), exist_ok=True)
    with open(path_out, "w", encoding="utf-8") as fh:
        fh.write(
            "% =====================================================================\n"
            "%  IEA <-> SISEPUEDE crosswalk table (auto-generated).\n"
            f"%  Source CSV : {path_in}\n"
            "%  Generator  : sisepuede/calibration/crosswalk_to_latex.py\n"
            "%  Do not edit by hand. Regenerate with:\n"
            "%      python -m sisepuede.calibration.crosswalk_to_latex\n"
            "% =====================================================================\n\n"
        )
        fh.write(tex)

    return path_out


def _render_fuel_map_table() -> str:
    """Render the canonical IEA-code -> SSP fuel-suffix mapping as a LaTeX
    tabular snippet. Reads ``IEA_FUEL_MAP`` directly from
    ``_iea_fuel_map.py`` so any edits there propagate automatically."""

    # Local import so this script can also be executed without the full
    # sisepuede package on the path; the module has no third-party deps.
    sys.path.insert(0, _REPO_ROOT)
    from sisepuede.calibration._iea_fuel_map import IEA_FUEL_MAP, agg_type

    head = r"""\begingroup
\small
\renewcommand{\arraystretch}{1.2}
\begin{table}[h!]
\centering
\begin{tabular}{@{}p{0.18\linewidth} p{0.10\linewidth} p{0.62\linewidth}@{}}
\toprule
IEA fuel code & Agg. & SSP fuel suffix(es) \\
\midrule
"""

    body_lines = []
    # Preserve the dict order from _iea_fuel_map.py so the table reads as
    # the source file does.
    for iea_code, suffixes in IEA_FUEL_MAP.items():
        agg = agg_type(iea_code)
        suffix_str = ", ".join(
            r"\texttt{" + _escape_latex(s) + "}" for s in suffixes
        )
        body_lines.append(
            f"{_escape_latex(iea_code)} & "
            f"{_escape_latex(agg)} & "
            f"{suffix_str} \\\\"
        )

    tail = r"""
\bottomrule
\end{tabular}
\caption{Canonical IEA fuel code $\to$ SISEPUEDE fuel suffix mapping. The \emph{Agg.} column is \texttt{sum} when more than one SSP suffix maps to the IEA code (the SSP fields must be added before comparison) and \texttt{direct} otherwise. \emph{Generated by} \texttt{crosswalk\_to\_latex.py} from \texttt{\_iea\_fuel\_map.py}.}\label{tab:fuel_map}
\end{table}
\endgroup
"""
    return head + "\n".join(body_lines) + tail


def build_fuel_map_table(path_out: str) -> str:
    """Write the IEA fuel-map table to ``path_out``. Returns ``path_out``."""
    tex = _render_fuel_map_table()
    os.makedirs(os.path.dirname(path_out), exist_ok=True)
    with open(path_out, "w", encoding="utf-8") as fh:
        fh.write(
            "% =====================================================================\n"
            "%  IEA fuel-code -> SSP suffix mapping table (auto-generated).\n"
            "%  Source     : sisepuede/calibration/_iea_fuel_map.py (IEA_FUEL_MAP)\n"
            "%  Generator  : sisepuede/calibration/crosswalk_to_latex.py\n"
            "%  Do not edit by hand. Regenerate with:\n"
            "%      python -m sisepuede.calibration.crosswalk_to_latex\n"
            "% =====================================================================\n\n"
        )
        fh.write(tex)
    return path_out


def main() -> None:
    p = argparse.ArgumentParser(
        description="Render the IEA <-> SISEPUEDE crosswalk and fuel-map as LaTeX tables.",
    )
    p.add_argument("--in",  dest="path_in",  default=DEFAULT_IN,
                   help=f"Path to the crosswalk CSV (default: {DEFAULT_IN}).")
    p.add_argument("--out", dest="path_out", default=DEFAULT_OUT,
                   help=f"Path to the crosswalk output .tex (default: {DEFAULT_OUT}).")
    p.add_argument("--fuel-map-out", dest="path_fuel_map_out",
                   default=DEFAULT_FUEL_MAP_OUT,
                   help=f"Path to the fuel-map output .tex (default: {DEFAULT_FUEL_MAP_OUT}).")
    args = p.parse_args()

    out_xw = build_table(args.path_in, args.path_out)
    print(f"Wrote crosswalk table to: {out_xw}")

    out_fm = build_fuel_map_table(args.path_fuel_map_out)
    print(f"Wrote fuel-map table to: {out_fm}")


if __name__ == "__main__":
    main()
